[package]
name = "arp-scan"
description = "A minimalistic ARP scan tool"
license = "AGPL-3.0-or-later"
version = "0.13.0"
authors = ["Saluki"]
edition = "2021"
readme = "README.md"
homepage = "https://github.com/Saluki/arp-scan-rs"
repository = "https://github.com/Saluki/arp-scan-rs"
keywords = ["arp", "scan", "network", "security"]
categories = ["command-line-utilities"]
exclude = ["/.semaphore", "/data", "/release.sh", ".*"]

[dependencies]

# CLI & utilities
clap = { version = "3", default-features = false, features = ["std", "suggestions", "color"] }
ansi_term = "0.12"
rand = "0.8"
ctrlc = "3.2"

# Network
pnet = "0.29"
ipnetwork = "0.18"
dns-lookup = "1.0"

# Parsing & exports
csv = "1.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
serde_yaml = "~0.8.17"
