[package]
name = "arp-scan"
description = "A minimalistic ARP scan tool"
license = "AGPL-3.0-or-later"
version = "0.3.0"
authors = ["Saluki"]
edition = "2018"
readme = "README.md"
homepage = "https://github.com/Saluki/arp-scan-rs"
repository = "https://github.com/Saluki/arp-scan-rs"
keywords = ["arp", "scan", "network", "security"]
categories = ["command-line-utilities"]

[dependencies]
pnet = "0.28.0"
ipnetwork = "0.18.0"
clap = "2.33.3"
dns-lookup = "1.0.6"
